name: github-issues-automation
description: Automate github issues

inputs:
  github-token:
    required: true
    description: Github token with permissions to modify projects

  organization:
    required: false
    description: The github organization (Required only if the project number is present)

  issue-action:
    required: false
    description: The type of action you would like to perform (update, delete, archive, create)
    default: update

  project-number:
    required: false
    description: The github project number (If the issue is part of a project)

  target-status:
    required: false
    description: The target status of the issue (Requires the issue to be part of a project)

  debug:
    required: false
    description: Sets debug logs on or off (true or false)
    default: "false"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - id: github-issues-automation
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ORGANIZATION: ${{ inputs.organization }}
        PROJECT_NUMBER: ${{ inputs.project-number }}
        TARGET_STATUS: ${{ inputs.target-status }}
        ISSUE_ACTION: ${{ inputs.issue-action }}
        DEBUG: ${{ inputs.debug }}
      shell: bash
      run: 
        go build && ./github-issues-automation
