name: Go

on:
  issues:
    types:
      - assigned

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
  
    - name: Github issues automation
      uses: tavh/github-issues-automation@v1
      with:
        github-token: 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
        project-number: 4
        target-status: "In Progress"
        organization: tav-test-org
        debug: true
    
